Name <- readline(prompt = "Enter the Name: ")
College <- readline(prompt = "Enter the College: ")
Branch <- readline(prompt = "Enter the Branch: ")
print(paste("My name is", Name, "I am studying in", College, "and of the branch", Branch))
print(paste("R Version:", R.version.string))
